config/routes.rb
Rails.application.routes.draw do
  resources :user_items
  resources :users
  resources :items do
    member do
      get :delete
    end
  end
 
  root 'user_items#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :user
    validates :title, presence: true
    validates :author, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :item
end

app/models/user_item.rb
class UserItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  def delete
    @item = Item.find(params[:id])
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
      #if true
        #format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.html { redirect_to items_path, notice: "Book '#{@item.title}' was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
      #if true
      #format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.html { redirect_to items_path, notice: "Book '#{@item.title}' was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    title = @item.title
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_path, notice: "Book '#{title}' was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      #params.require(:item).permit(:title, :author, :price, :date)
      params.require(:item).permit(:title, :author, :price, :date)
    end
end

app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController
  before_action :set_user_item, only: %i[ show edit update destroy ]

  # GET /user_items or /user_items.json
  def index
    @user_items = UserItem.all
    @users = User.all
    @items = Item.all
  end

  # GET /user_items/1 or /user_items/1.json
  def show
  end

  # GET /user_items/new
  def new
    @user_item = UserItem.new
  end

  # GET /user_items/1/edit
  def edit
  end

  # POST /user_items or /user_items.json
  def create
    @user_item = UserItem.new(user_item_params)

    respond_to do |format|
      if @user_item.save
        format.html { redirect_to user_item_url(@user_item), notice: "User item was successfully created." }
        format.json { render :show, status: :created, location: @user_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_items/1 or /user_items/1.json
  def update
    respond_to do |format|
      if @user_item.update(user_item_params)
        format.html { redirect_to user_item_url(@user_item), notice: "User item was successfully updated." }
        format.json { render :show, status: :ok, location: @user_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_items/1 or /user_items/1.json
  def destroy
    @user_item.destroy

    respond_to do |format|
      format.html { redirect_to user_items_url, notice: "User item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_item
      @user_item = UserItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_item_params
      params.require(:user_item).permit(:user_id, :item_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_items_helper.rb
module UserItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/delete.html.erb
<h1>Delete Book</h1>

<%= form_for(@item, :method => 'delete') do |form| %>
    <p>Are you sure you want to delete this book?</p>
    <p><%= @item.title %></p>

    <div class ="form-buttons">
        <%= form.submit("Delete Book") %>
    </div>
    <% end %>

<br>
<%= link_to 'Back', items_path %>

app/views/items/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@item, :method => 'patch') do |form| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
            <% @item.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :author %>
        <%= form.text_field :author %>
    </div>

    <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price %>
    </div>

    <div class="field">
        <%= form.label :date %>
        <%= form.date_select :date, :order => [:day, :month, :year] %>
    </div>

    <div class ="form-buttons">
        <%= form.submit("Update Book") %>
    </div>
    <% end %>
<br>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th>Published Date</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.author %></td>
        <td><%= item.price %></td>
        <td><%= item.date %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Delete', delete_item_path(item) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_item_path %>

app/views/items/new.html.erb
<h1>New Book</h1>

<%= form_for(@item, :method => 'post') do |form| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
            <% @item.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :author %>
        <%= form.text_field :author %>
    </div>

    <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price %>
    </div>

    <div class="field">
        <%= form.label :date %>
        <%= form.date_select :date, :order => [:day, :month, :year] %>
    </div>

    <div class ="form-buttons">
        <%= form.submit("Create Book") %>
    </div>

    <% end %>

<br>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @item.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Published Date:</strong>
  <%= @item.date %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_items/_form.html.erb
<%= form_with(model: user_item) do |form| %>
  <% if user_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_item.errors.count, "error") %> prohibited this user_item from being saved:</h2>

      <ul>
        <% user_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, User.order(:username).map { |user| [user.username, user.id] }, include_blank: true, id: "id_of_the_user_id_select_box" %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.select :item_id, Item.order(:title).map { |item| [item.title, item.id] }, include_blank: true, id: "id_of_the_item_id_select_box" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_items/edit.html.erb
<h1>Editing User Book</h1>

<%= render 'form', user_item: @user_item %>

<%= link_to 'Show', @user_item %> |
<%= link_to 'Back', user_items_path %>

app/views/user_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Books</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Book Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_items.each do |user_item| %>
      <tr>
        <td><%= User.where(id: user_item.user_id).last.username %></td>
        <td><%= Item.where(id: user_item.item_id).last.title %></td>
        <td><%= link_to 'Show', user_item %></td>
        <td><%= link_to 'Edit', edit_user_item_path(user_item) %></td>
        <td><%= link_to 'Destroy', user_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Book', new_user_item_path %>

<br>

<%= link_to 'Book Index', items_path %>

<br>

<%= link_to 'User Index', users_path %>

app/views/user_items/new.html.erb
<h1>New User Book</h1>

<%= render 'form', user_item: @user_item %>

<%= link_to 'Back', user_items_path %>

app/views/user_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_item.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @user_item.item_id %>
</p>

<%= link_to 'Edit', edit_user_item_path(@user_item) %> |
<%= link_to 'Back', user_items_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>